---
- name: Install and configure Nginx on Ubuntu, Debian, and RedHat
  hosts: all
  become: true
  gather_facts: true
  vars:
    index_page_content: |
      <html>
      <head><title>Welcome</title></head>
      <body><h1>Welcome to Nginx!</h1></body>
      </html>

  tasks:
    - name: Gather OS details
      set_fact:
        os_family: "{{ ansible_os_family }}"
        os_distribution: "{{ ansible_distribution | lower }}"

    - name: Set SSH user for Ubuntu
      set_fact:
        ansible_user: ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Nginx on Debian
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_distribution == "Debian"

    - name: Install Nginx on RedHat/CentOS
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create index.html for Nginx welcome page
      copy:
        dest: /var/www/html/index.html
        content: "{{ index_page_content }}"
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Create index.html for RedHat-based systems
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "{{ index_page_content }}"
      when: ansible_os_family == "RedHat"

    - name: Reload systemd daemon if required
      command: systemctl daemon-reexec
      when: ansible_os_family != "Windows"
      changed_when: false

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
